# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cad_cate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cad_categoria(object):
    def setupUi(self, cad_categoria):
        cad_categoria.setObjectName("cad_categoria")
        cad_categoria.resize(472, 184)
        cad_categoria.setMinimumSize(QtCore.QSize(472, 184))
        cad_categoria.setMaximumSize(QtCore.QSize(472, 184))
        self.label = QtWidgets.QLabel(cad_categoria)
        self.label.setGeometry(QtCore.QRect(10, 10, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(cad_categoria)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 431, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lb_nome = QtWidgets.QLabel(self.groupBox)
        self.lb_nome.setGeometry(QtCore.QRect(10, 30, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb_nome.setFont(font)
        self.lb_nome.setObjectName("lb_nome")
        self.txt_nome = QtWidgets.QLineEdit(self.groupBox)
        self.txt_nome.setGeometry(QtCore.QRect(70, 30, 351, 31))
        self.txt_nome.setObjectName("txt_nome")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 411, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_cad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_cad.setObjectName("bt_cad")
        self.horizontalLayout.addWidget(self.bt_cad)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_pesq = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_pesq.setObjectName("bt_pesq")
        self.horizontalLayout.addWidget(self.bt_pesq)

        self.retranslateUi(cad_categoria)
        QtCore.QMetaObject.connectSlotsByName(cad_categoria)
        cad_categoria.setTabOrder(self.txt_nome, self.bt_cad)
        cad_categoria.setTabOrder(self.bt_cad, self.bt_pesq)

    def retranslateUi(self, cad_categoria):
        _translate = QtCore.QCoreApplication.translate
        cad_categoria.setWindowTitle(_translate("cad_categoria", "Cadastrar Categoria"))
        self.label.setText(_translate("cad_categoria", "<html><head/><body><p align=\"center\">Cadastrar Categoria</p></body></html>"))
        self.groupBox.setTitle(_translate("cad_categoria", "Cadastro"))
        self.lb_nome.setText(_translate("cad_categoria", "<html><head/><body><p align=\"right\">Nome:</p></body></html>"))
        self.bt_cad.setText(_translate("cad_categoria", "Cadastrar"))
        self.bt_pesq.setText(_translate("cad_categoria", "Pesquisar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cad_categoria = QtWidgets.QWidget()
    ui = Ui_cad_categoria()
    ui.setupUi(cad_categoria)
    cad_categoria.show()
    sys.exit(app.exec_())
