# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_cat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_cat(object):
    def setupUi(self, edit_cat):
        edit_cat.setObjectName("edit_cat")
        edit_cat.resize(581, 217)
        self.label = QtWidgets.QLabel(edit_cat)
        self.label.setGeometry(QtCore.QRect(10, 10, 561, 31))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(edit_cat)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 561, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.txt_nome = QtWidgets.QLineEdit(self.groupBox)
        self.txt_nome.setGeometry(QtCore.QRect(70, 30, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.txt_nome.setFont(font)
        self.txt_nome.setMaxLength(100)
        self.txt_nome.setObjectName("txt_nome")
        self.lb_nome = QtWidgets.QLabel(self.groupBox)
        self.lb_nome.setGeometry(QtCore.QRect(10, 30, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lb_nome.setFont(font)
        self.lb_nome.setObjectName("lb_nome")
        self.horizontalLayoutWidget = QtWidgets.QWidget(edit_cat)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 561, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_salvar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_salvar.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bt_salvar.setFont(font)
        self.bt_salvar.setObjectName("bt_salvar")
        self.horizontalLayout.addWidget(self.bt_salvar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_return = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bt_return.setFont(font)
        self.bt_return.setObjectName("bt_return")
        self.horizontalLayout.addWidget(self.bt_return)

        self.retranslateUi(edit_cat)
        QtCore.QMetaObject.connectSlotsByName(edit_cat)

    def retranslateUi(self, edit_cat):
        _translate = QtCore.QCoreApplication.translate
        edit_cat.setWindowTitle(_translate("edit_cat", "Editar Categoria"))
        self.label.setText(_translate("edit_cat", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Editar Categoria Selecionada</span></p><p align=\"center\"><br/></p></body></html>"))
        self.groupBox.setTitle(_translate("edit_cat", "Editar"))
        self.lb_nome.setText(_translate("edit_cat", "<html><head/><body><p align=\"right\">Nome:</p></body></html>"))
        self.bt_salvar.setText(_translate("edit_cat", "Salvar"))
        self.bt_return.setText(_translate("edit_cat", "Retornar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_cat = QtWidgets.QWidget()
    ui = Ui_edit_cat()
    ui.setupUi(edit_cat)
    edit_cat.show()
    sys.exit(app.exec_())
