# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_deletar(object):
    def setupUi(self, Dialog_deletar):
        Dialog_deletar.setObjectName("Dialog_deletar")
        Dialog_deletar.resize(341, 109)
        Dialog_deletar.setToolTip("")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_deletar)
        self.buttonBox.setGeometry(QtCore.QRect(10, 70, 321, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog_deletar)
        self.label.setGeometry(QtCore.QRect(10, 0, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_deletar)
        self.buttonBox.accepted.connect(Dialog_deletar.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_deletar.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_deletar)

    def retranslateUi(self, Dialog_deletar):
        _translate = QtCore.QCoreApplication.translate
        Dialog_deletar.setWindowTitle(_translate("Dialog_deletar", "Deseja Excluir?"))
        self.label.setToolTip(_translate("Dialog_deletar", "<html><head/><body><p><span style=\" font-size:10pt;\">O produto sera excluido permanentemente</span></p></body></html>"))
        self.label.setWhatsThis(_translate("Dialog_deletar", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("Dialog_deletar", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Deseja Excluir o produto do estoque?</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_deletar = QtWidgets.QDialog()
    ui = Ui_Dialog_deletar()
    ui.setupUi(Dialog_deletar)
    Dialog_deletar.show()
    sys.exit(app.exec_())
